require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '12.0'
$FirebaseSDKVersion = '8.10.0'

target 'Bmad' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path


  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  target 'BmadTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  # use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})

  post_install do |installer|
    react_native_post_install(installer)
    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    # end
  end
end
